markdown: kramdown

kramdown:
   input: GFM
   syntax_highlighter: rouge

#added for jekyll3 20160212
#gems: [jekyll-paginate]
plugins: [jekyll-paginate]
 
# Permalinks
permalink:        pretty

# Setup
title:            Robert Cudmore
tagline:          ''
description:      'Robert Cudmore Blog'
url:              http://cudmore.github.io

# Keep as an empty string if served up at the root. If served up at a specific
# path (e.g. on GitHub pages) leave off the trailing slash, e.g. /my-project
baseurl: ''

author:
  name:           'Robert Cudmore'
  url:            http://robertcudmore.org

paginate:         7

# Custom vars
version:          0.2

github:
  repo:           https://github.com/cudmore/cudmore.github.io

#a simple database of pages, used in header.html
#following http://joshualande.com/jekyll-github-pages-poole/
pages_list:       
  #Home: '/index.html'
  #about: '/about'
  archive: '/archive'
  tags: '/tags'
  search: '/search'
  software: '/software'
  #feed: '/atom.xml'