# Dependencies
# markdown:         redcarpet
#redcarpet:
#  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "strikethrough", "superscript"]
# highlighter:      pygments

# may 2015, this was causing problems on osx
#gems:
#  - jekyll-sitemap

#added for jekyll3 20160212
gems:
    - jekyll-paginate

 
# Permalinks
permalink:        pretty
# relative_permalinks: true

# Setup
title:            Robert Cudmore
tagline:          ''
description:      'Robert Cudmore Blog'
url:              http://blog.cudmore.io

# Keep as an empty string if served up at the root. If served up at a specific
# path (e.g. on GitHub pages) leave off the trailing slash, e.g. /my-project
baseurl: ''
# was this
#baseurl:          /

author:
  name:           'Robert Cudmore'
  url:            http://robertcudmore.org

paginate:         5

# Custom vars
version:          0.1

github:
  repo:           https://github.com/cudmore/cudmore.github.io

#a simple database of pages, used in header.html
#following http://joshualande.com/jekyll-github-pages-poole/
pages_list:       
  #Home: '/index.html'
  about: '/about'
  archive: '/archive'
  tags: '/tags'
  software: '/software'
  #feed: '/atom.xml'